on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: mihirdarji1/python-scripts/.github/actions/docker-action@v1.0.0
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: print github output
        run: echo $GITHUB_OUTPUT

       name: Hello world action version 2
        id: hello
        uses: mihirdarji1/python-scripts/.github/actions/docker-action@v2.0.0
        with: 
          who-to-greet: 'v2.0.0'
      # Use the output from the `hello` step
      - name: Get the output time of version 2
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: print github output version 2
        run: echo $GITHUB_OUTPUT
